### PR TITLE
Adding in Unit Tests and performing necessary refactors

### PR DESCRIPTION
**Pull request by secondsun**
This includes tests for the OAuth template.

#How to test

Make sure you have a device in debug mode or an emulator attached and running.

```bash
./gradlew connectedCheck
```
Should pass.

### CODE REVIEW

**Comment by secondsun** [comment]
@danielpassos @wei-lee @corinnekrych  :eyes: ?

**Comment by danielpassos** [comment]
@secondsun Let's remove the credentials from `app/src/main/assets/fhconfig.properties`

**Comment by danielpassos** [comment]
```
com.feedhenry.helloworld.test.FOAuthAbstractClassTest > testLoginButtonShowsIfNotLoggedIn[Google Nexus 6 - 5.1.0 - API 22 - 1440x2560 - 5.1] FAILED
	junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)
:app:connectedDebugAndroidTest FAILED
```

**index.html**

```
junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.feedhenry.helloworld.test.FOAuthAbstractClassTest.testLoginButtonShowsIfNotLoggedIn(FOAuthAbstractClassTest.java:109)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at junit.framework.TestResult.runProtected(TestResult.java:133)
at android.support.test.internal.runner.junit3.DelegatingTestResult.runProtected(DelegatingTestResult.java:90)
at junit.framework.TestResult.run(TestResult.java:118)
at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:49)
at junit.framework.TestCase.run(TestCase.java:124)
at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:63)
at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:228)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
```

**Comment by danielpassos** [comment]
:+1:

**Pull request merged**
